name: Lightning Talk Proposal
description: Suggestion for a lightning talk
title: "Lightning Talk Proposal: \"#{your title here}\""
labels: [Lightning Talk]
body:
  - type: input
    attributes:
      label: Your name
      placeholder: "Alonzo"

  - type: textarea
    attributes:
      label: Your GitHub/Social Link/personal Website
      placeholder: "https://github.com/alonzo_church | https://bsky.app/profile/alonzo_church.bsky.social | alonzochurch.com (optional)"

  - type: input
    attributes:
      label: "Title of your presentation"
      placeholder: "`alias`, `import`, `require`, `use` in Elixir"

  - type: textarea
    attributes:
      label: Description
      placeholder: "On how to differentiate them"
